name: tiebanshenshu_example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  tiebanshenshu:
    path: ../
  repository_interface_tiebanshenshu:
    git:
      url: http://192.168.0.165:3000/xuan/repository-interface-tiebanshenshu.git
  persistence_assets:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: assets

  provider: any
  timezone: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5

  metaphysics_core: any
  logger: any
flutter:
  uses-material-design: true

  assets:
    - assets/all_tiao_wen_v1.csv
    - assets/formulas/
    - assets/kao_ke/

dependency_overrides:
  persistence_core:
    path: ../../xuan-storage/core
  metaphysics_core:
    path: ../../xuan-metaphysics-core
  repository_interface_tiebanshenshu:
    path: ../../repository-interface-tiebanshenshu
  xuan_gua_core:
    path: ../../xuan-gua-core
  persistence_assets:
    path: ../../xuan-storage/assets
